name: monopoly
description: Monopoly Calculator calculate and figure out the net worth of the Monopoly game winner.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  intl: ^0.15.8

  firebase_auth: ^0.11.1+11
  firebase_database: ^3.0.4
  google_sign_in: ^4.0.4

  rflutter_alert: ^1.0.3
  flutter_inner_drawer: ^0.5.4
  flutter_colorpicker: ^0.2.1

  shared_preferences: ^0.5.2+1

  flutter_bloc: ^3.2.0
  http: ^0.12.0+4
  equatable: ^1.1.1


dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"

# For information on the generic Dart pa]rt of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/monstera.png
   - assets/images/aloe_vera.png
   - assets/images/bird_of_paradise.png
   - assets/images/cat_palm.png
   - assets/images/google_logo.png
   - assets/images/background.jpg
   - assets/images/plant_logo.png
   - assets/images/plantify_logo.png
   - assets/images/icon_home.png
   - assets/images/icon_search.png
   - assets/images/icon_menu.png
   - assets/images/icon_plant.png
   - assets/images/icon_add.png
   - assets/images/icon_user.png
   - assets/images/monopoly_logo.png
   - assets/images/credit_card/money_symbol.png
   - assets/images/credit_card/chip.png
   - assets/images/credit_card/nfc.png
   - assets/images/credit_card/visa.png
   - assets/images/credit_card/monopoly.png
   - assets/images/freeze.png
   - assets/images/more.png
   - assets/images/passbook.png
   - assets/images/secret.png
   - assets/images/transfer.png
   - assets/images/unlock.png
   - assets/images/send.png
   - assets/images/thousand.png
   - assets/images/million.png
   - assets/images/pay.png
   - assets/images/clear.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf 
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family:  PlantifyBottomNavIcons
      fonts:
        - asset: assets/fonts/PlantifyBottomNavIcons.ttf
    - family:  MonopolyIcon
      fonts:
        - asset: assets/fonts/MonopolyIcon.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
